### PR TITLE
Force markdown to recognise URLs

### PR DESCRIPTION
**Pull request by tibs**
Unfortunately the two "bare" URLs in my talk pages don't show up as such on the actual web site. So I've gone more explicit.

### CODE REVIEW

**Comment by alexwlchan** [comment]
This is fine as-is, but Markdown has a simpler syntax for raw URLs: wrapping them in angle brackets, i.e.

```markdown
<https://github.com/tibs/markup-history>
```

is equivalent to

```
[https://github.com/tibs/markup-history](https://github.com/tibs/markup-history)
```

---

Rendered example:

<https://github.com/tibs/markup-history>
[https://github.com/tibs/markup-history](https://github.com/tibs/markup-history)

**Comment by tibs** [comment]
I looked up the github markdown documentation, which is why I just used bare URLs, expecting them to render. As you say, the angle bracket format is also documented as working (it must make hell for the parser trying not to recognise it as HTML!), but I didn't know if that would work or not, given my first attempt didn't. So I went full-explicit.

I'm very happy to try the shorter (and more obvious) form, but just worried I'll need to go around again.

**Comment by alexwlchan** [comment]
Okay, no worries. Merging as-is.

**Comment by alexwlchan** [comment]
> it must make hell for the parser trying not to recognise it as HTML!

It might if Markdown used a parser, but it just uses a regex (or Markdown.pl does, at least):

```perl
$text =~ s{<((https?|ftp):[^'">\s]+)>}{<a href="$1">$1</a>}gi;
```

Non-standard URL schemes don’t get this special treatment.

**Pull request merged**
