### PR TITLE
update my workshop page with detailed installation instructions

### PR DESCRIPTION
**Pull request by hjwp**

### CODE REVIEW

**Review by alexwlchan — APPROVED** [review]

**Comment by alexwlchan** [comment]
Detailed! 👌

**Comment by hjwp** [comment]
oh the code blocks came out all weird (basically as `<code>` blocks instead of `<pre>`.  any idea what i should do to get `<pre>`?  is inline html supported?

**Comment by alexwlchan** [comment]
I would have expected them to come out as `<pre>`, looking at the source Markdown. Inline HTML is probably supported, but I don’t have time to look at this right now (I need to get to bed!).

I’ll try to find time to look tomorrow.

**Comment by hjwp** [comment]
thought i'd try and run a copy of the site locally but i'm just seeing 500s, cant `buildsite` or `manage.py serve`..

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/harry/.virtualenvs/2017.pyconuk.org/lib/python3.6/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/harry/.virtualenvs/2017.pyconuk.org/lib/python3.6/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/harry/.virtualenvs/2017.pyconuk.org/lib/python3.6/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/harry/.virtualenvs/2017.pyconuk.org/lib/python3.6/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/harry/.virtualenvs/2017.pyconuk.org/lib/python3.6/site-packages/django_amber/management/commands/buildsite.py", line 20, in handle
    self.buildsite(port)
  File "/home/harry/.virtualenvs/2017.pyconuk.org/lib/python3.6/site-packages/django_amber/management/commands/buildsite.py", line 33, in buildsite
    rsp.raise_for_status()
  File "/home/harry/.virtualenvs/2017.pyconuk.org/lib/python3.6/site-packages/requests/models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:53921/
```

**Comment by alexwlchan** [comment]
Set `debug = True` in `settings.py` to get a possibly more useful traceback.

**Comment by hjwp** [comment]
`lessc` not found!  thanks alex, should have thought of that, fixing...

**Comment by hjwp** [comment]
choo choo!  here comes a new version #180 :steam_locomotive:

**Pull request merged**
