### PR TITLE
Close ticket sales

### PR DESCRIPTION
**Pull request by inglesp**

### CODE REVIEW

**Comment by alexwlchan** [comment]
Why are these builds failing? D:

**Comment by inglesp** [comment]
Dunno!  `make build` works fine for me locally.  But I've retried three times now, so it's obviously more than just a transient error.

**Comment by alexwlchan** [comment]
Interesting, I do get issues locally. Digging into it…

**Comment by alexwlchan** [comment]
(Wait, that’s because I don’t have node installed.)

**Comment by alexwlchan** [comment]
Ah wait, Travis started failing *after* we merged #104, I wonder if that’s the issue?

**Comment by inglesp** [comment]
Hunch: it now takes so long to load pages into the local database on Travis, that this hasn't completed by the time whatever it is that scrapes the site starts scraping.

**Comment by alexwlchan** [comment]
Seems plausible:

```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: pyconuk_page
```

**Comment by inglesp** [comment]
`runserver_in_process` [doesn't actually fail](https://github.com/inglesp/django-amber/blob/master/src/django_amber/utils.py#L14-L41) if it takes longer than a couple of seconds for the server to start.

**Comment by inglesp** [comment]
Well, it would fail on `requests.exceptions.ConnectionError`, but not on a 500.

@alexwlchan Where are you seeing that `OperationalError`?

**Comment by alexwlchan** [comment]
> Where are you seeing that `OperationalError`?

I just pushed an additional commit to this branch – pull requests in Travis now run with DEBUG=True, so we get more useful tracebacks.

**Comment by inglesp** [comment]
Neato.

So I suggest the fix for now is to increase the timeout in django-amber.

**Comment by alexwlchan** [comment]
Okay. You know django-amber better than I do, so could I leave you to do that and go to bed please? :-)

**Comment by inglesp** [comment]
Sure!  Thanks for your help.

**Comment by inglesp** [comment]
I think I've introduced another problem (`ModuleNotFoundError: No module named 'lessc {infile} {outfile}'`) by being careless with dependencies when I bundled django_amber.

For now, I'll deploy manually (with `./deploy.sh`, assuming that still works).

**Pull request merged**
