### PR TITLE
2017 skin

### PR DESCRIPTION
**Pull request by hawkz**
This isn't ready to merge, but wanted to show the progress. Ask what info we could include to make the footer more valuable?

### CODE REVIEW

**Comment by inglesp** [comment]
Hi @hawkz -- looks like a good start!

This obviously isn't finished, so I'll hold off adding any comments until you're ready.

To answer your question about the footer: could you add "design by Blanc"?  I don't think we need anything else.

**Comment by meatballs** [comment]
Well, it's certainly an improvement on my current effort!

**Comment by hawkz** [comment]
Ok @meatballs @inglesp I think it's ready for review. The obvious gap is the footer, that needs input on what we want to have there, so I have some material to work with (bit of a content vacuum there) but the rest is now looking ok - I think! ;)

Would love to get feedback and then I can hammer through any changes and the footer, as we move to launch.

Looking through the 2016 site, it's mostly 'normal' content or the schedule, with the exception of the blog-y news area. What's the plan with that part?

**Comment by hawkz** [comment]
@inglesp just re-ready your comment, I think we had a twitter & youtube link before. Trying to think of useful value we could add there. Maybe a repeat of navigation. If not, I'll reduce the amount of space and simplify it down.

**Comment by hawkz** [comment]
One idea for the footer could be a high-level outline of conference timings, like RfPs, close of RfPs, schedule publish date etc.

**Comment by inglesp** [comment]
Hi @hawkz!  Thanks for all this.  It's good to be thinking about mobile from the outset.

My main first impression is that the jumbotron takes up too much vertical space on my laptop, pushing the content a long way off the bottom of the screen.  Is the idea to have the jumbotron as a page in its own right?  Or do you expect users to scroll down past the snakes and picture of City Hall to the content below?

Other stuff:
 * We're going to want a way to have a small branded header on each page.  Could you produce a sample for this, perhaps with blinking snakes?
 * Body fonts and colours look good
 * Snakes blinking: I love it.
 * Psychedelic flashing on rollover of tickets link: possibly too much?
 * Responsiveness of schedule is great, but we're missing information on which room each session is in.  I think it's not worth spending time on this now until we know more about the shape of the 2017 schedule.

**Comment by hawkz** [comment]
Thanks for the feedback @inglesp!

Looking for the action points then:
- Set max-height for jumbotron (good catch) it is way too big on some proportions.
- Design 'normal' page header (guessing for the set of pages we have would be useful)
- Toning down the rollover (I was shooting for the 'monty' in python - what needs to go?)
- On the schedule point, I figured on mobile you could go to the talk page.. or we could have them in each entry and hide for desktop etc. preference?
- Maybe we explore popups for talk details to save the bandwidth of the venue?

Then I think that's it?

**Comment by hawkz** [comment]
Any update on how I can move this forward?

**Comment by inglesp** [comment]
Hi @hawkz -- have you made the adjustments in your action points from https://github.com/PyconUK/2017.pyconuk.org/pull/1#issuecomment-281266073?

**Comment by hawkz** [comment]
I've started but I'm waiting on the answers to the questions in the last comment I made. Sorry if that's not been clear enough. Do my questions make sense?

**Comment by inglesp** [comment]
Hey @hawkz.

> Set max-height for jumbotron (good catch) it is way too big on some proportions.

Yes please!

> Design 'normal' page header (guessing for the set of pages we have would be useful)

Yes please!

> Toning down the rollover (I was shooting for the 'monty' in python - what needs to go?)

Leave it as it is for now -- most people I've shown it to like it!

> On the schedule point, I figured on mobile you could go to the talk page.. or we could have them in each entry and hide for desktop etc. preference?

If at all possible, we should include the room for each talk, and hide on desktop.

> Maybe we explore popups for talk details to save the bandwidth of the venue?

I don't think this would save much bandwidth (would it?) and likely would add complexity to the implementation of the site.  It's a nice idea though.

**Comment by inglesp** [comment]
Hi @hawkz -- how's this looking?

**Comment by hawkz** [comment]
@inglesp should be all good to go now! 💃

**Comment by inglesp** [comment]
Thanks for this @hawkz -- I'll have a crack at applying this to last year's website so that we can see what a full website looks like.

**Review by meatballs — APPROVED** [review]
Nice Job!

**Comment by inglesp** [comment]
This new design is now live.

Thanks @hawkz and @moreati for your work!

**Pull request closed without merging**
