### PR TITLE
Update preliminary schedule for unavailability

### PR DESCRIPTION
**Pull request by meatballs**

### CODE REVIEW

**Comment by meatballs** [comment]
Nudge

**Comment by inglesp** [comment]
It's a bit fiddly to review this properly, as several sessions have moved position in the list, but are still on the same day.  It looks like this is because sessions are being sorted differently to how they were before.

Any chance you could split it up into two commits -- one to reorder sessions, and one to change days?

**Comment by meatballs** [comment]
Not easily. It's produced by scripts and I'm not entirely sure why the sort order has changed in the first place. 

On 2 September 2017 07:18:06 BST, Peter Inglesby <notifications@github.com> wrote:
>It's a bit fiddly to review this properly, as several sessions have
>moved position in the list, but are still on the same day.  It looks
>like this is because sessions are being sorted differently to how they
>were before.
>
>Any chance you could split it up into two commits -- one to reorder
>sessions, and one to change days?

-- 
Owen Campbell 

This email has been digitally signed. 
For further information visit http://owencampbell.me.uk/pgp

**Comment by inglesp** [comment]
OK.  Assuming that the changes in the scheduling repo were checked, I'll merge this.

**Pull request merged**
