### PR TITLE
Add session chairs schedule

### PR DESCRIPTION
**Pull request by meatballs**

### CODE REVIEW

**Comment by inglesp** [comment]
Is this generated off anything?

**Comment by meatballs** [comment]
[content hand cranked from spreadsheet](https://github.com/PyconUK/2017-scheduler/blob/master/solution/chairs.yml )
plus
[script to build the markdown](https://github.com/PyconUK/2017-scheduler/blob/master/utils/build_chairs_schedule.py)

**Comment by inglesp** [comment]
OK!  Could you add a comment to the top of both schedules to say that if you edit one you must edit the other one?  (Anything above the `---` is YAML, so you can use `# yaml comments`.)

**Comment by meatballs** [comment]
how about  - 'don't edit this. It's automatically generated'? (or similar)

**Comment by inglesp** [comment]
Also fine.

**Pull request merged**
