### PR TITLE
Add a responsive fix for 1200-1680px widths

### PR DESCRIPTION
**Pull request by hawkz**
Try to prevent overlap with the new shape of content we have.

### CODE REVIEW

**Comment by inglesp** [comment]
This is a fix for #6.  @Lukasa and/or @meshy, could you try this out?

**Comment by Lukasa** [comment]
Doesn't seem like this works for me, either on small viewports:

screen shot 2017-06-21 at 08 20 55

Or on wide:

screen shot 2017-06-21 at 08 21 00

**Comment by meshy** [comment]
I'm afraid I've not been able to build this project locally (I was able to make the modifications to the CSS last time). I'll open an issue for that.

**Comment by meshy** [comment]
Not ideal for me either :/

screenshot from 2017-06-21 08-41-30

**Comment by inglesp** [comment]
I think this is Good Enough, since we'll change this to something like "Register now" on July 2nd.

@Lukasa or @meshy, would you be able to see whether changing "Tickets on sale 25th June" to "Register now" in templates/index.html looks OK to you?

**Comment by inglesp** [comment]
Closing as this has been quiet for a month.

**Pull request closed without merging**
