### PR TITLE
The Zen of PyCon UK

### PR DESCRIPTION
**Pull request by tjguk**
I'm tentatively proposing this PR to include a "Zen of PyCon UK" in the front page text under "Atmosphere". I'm not wedded to it -- but I wanted at least to put it forward as I think it might be helpful and in keeping with our general spirit / ethos.

### CODE REVIEW

**Comment by ntoll** [comment]
This is a thing of beauty. I whole heartedly back this. +10000000000000000000000000000000000000000 from me.

**Comment by inglesp** [comment]
I have a couple of suggested alterations:

Instead of:

    Never be afraid to gracefully but firmly call someone out for negative behaviour, implicit or explicit

could we have:

    Never be afraid to address, politely, negative behaviour or language, whether explicit or implicit

?

And what about changing:

* Never be afraid to admit you're out of your depth

to

* Never be afraid to admit you're wrong, that you don't know, or that you're out of your depth
* Never be afraid to go in out of your depth
* Never act surprised just because someone seems not to know something you think they should

?

**Comment by tjguk** [comment]
I'm basically +1 on those changes (or, at least, +0.5). I like the intent of the last addition ("never act surprised...") but the wording seemed just a little convoluted. However I couldn't come up with a better alternative after a few moments' thought 😄

**Comment by ntoll** [comment]
Never act surprised at another's inexperience.

???

**Comment by meatballs** [comment]
Never express surprise at another's experience

**Pull request merged**
